dist: xenial
language: python
python:
- 3.5
- 3.6
- 3.7
sudo: required
before_install:
- sudo pip install --upgrade setuptools pip
- sudo pip install ansible==2.1.3.0
install:
- ansible-playbook --extra-vars="brozzler_pip_name=file://$TRAVIS_BUILD_DIR#egg=brozzler user=travis" --inventory-file=ansible/hosts-localhost ansible/playbook.yml
- pip install $TRAVIS_BUILD_DIR git+https://github.com/internetarchive/warcprox.git#egg=warcprox pytest==4.3.0
- chromium-browser --version
- sudo apt-get update
- sudo apt-get install --only-upgrade chromium-browser
- chromium-browser --version
- ps ww -fHe
- sudo cat /var/log/Xvnc.log
- sudo cat /var/log/brozzler-worker.log
- sudo cat /var/log/warcprox.log
script:
- DISPLAY=:1 py.test --tb=native -v tests
after_failure:
- chromium-browser --version
- sudo kill -QUIT $(sudo svstat /etc/service/warcprox | egrep -o 'pid [0-9]+' | awk '{print $2}')
- sudo kill -QUIT $(sudo svstat /etc/service/brozzler-worker | egrep -o 'pid [0-9]+' | awk '{print $2}')
- sudo cat /var/log/warcprox.log
- sudo cat /var/log/brozzler-worker.log
- sudo cat /var/log/pywb.log
